[package]
name = "fungible-cosmwasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = "2"
cosmwasm-schema = "2"
cw-storage-plus = "2"
schemars = "0.8"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[profile.release]
overflow-checks = true
lto = true
codegen-units = 1
panic = "abort"
